name: Test Auth

on: pull_request

env:
  # make chromedriver detect installed Chrome version and download the corresponding driver
  DETECT_CHROMEDRIVER_VERSION: true
  CHROMEDRIVER_CDNURL: https://npmmirror.com/metadata
  CHROMEDRIVER_CDNBINARIESURL: https://npmmirror.com/binaries

jobs:
  test-chrome:
    name: Test Auth on Chrome and Node If Changed
    runs-on: ubuntu-latest

    steps:
      # install Chrome first, so the correct version of webdriver can be installed by chromedriver
      # when setting up the repo
      - name: install Chrome stable
        run: |
          npx @puppeteer/browsers install chrome@stable
          npx @puppeteer/browsers install chromedriver@stable
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so run-changed script can diff properly.
          fetch-depth: 0
      - name: Set up Node (16)
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Bump Node memory limit
        run: echo "NODE_OPTIONS=--max_old_space_size=4096" >> $GITHUB_ENV
      - name: Test setup and yarn install
        run: |
          cp config/ci.config.json config/project.json
          yarn
      - name: build
        run: yarn build:changed auth
      - name: Run tests on changed packages
        run: xvfb-run yarn test:changed auth
  test-firefox:
    name: Test Auth on Firefox If Changed
    # Whatever version of Firefox comes with 22.04 is causing Firefox
    # startup to hang when launched by karma. Need to look further into
    # why.

    runs-on: ubuntu-20.04

    steps:
      - name: install Firefox stable
        run: |
          sudo apt-get update
          sudo apt-get install firefox
          sudo apt-get install wget
          npx @puppeteer/browsers install chrome@stable
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so run-changed script can diff properly.
          fetch-depth: 0
      - name: Set up Node (16)
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Bump Node memory limit
        run: echo "NODE_OPTIONS=--max_old_space_size=4096" >> $GITHUB_ENV
      - name: Test setup and yarn install
        run: |
          cp config/ci.config.json config/project.json
          yarn
      - name: build
        run: yarn build:changed auth
      - name: Run tests on auth changed packages
        run: xvfb-run yarn test:changed auth
        env:
          BROWSERS: 'Firefox'
